import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { prisma } from "../db/client";
import superjson from "superjson";
import ProductGrid from "../components/product/ProductGrid";
import { Prisma, Product, ProductPhoto } from "@prisma/client";

const Home: NextPage<{ products: any }> = ({ products }) => {
  console.log("Props", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Le Store</title>
        <meta
          name="description"
          content="A store generated by Leandro in NextJS + Prisma + tRPC"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Product list</h1>
        <ProductGrid products={products} />
      </main>

      <footer className={styles.footer}>Powered by me.</footer>
    </div>
  );
};

export const getServerSideProps = async () => {
  const products = await prisma?.product.findMany({
    include: { photos: true },
  });

  console.log(superjson.serialize(products).json);
  return {
    props: {
      products: superjson.serialize(products).json,
    },
  };
};

export default Home;
