import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { prisma } from "../db/client";
import superjson from "superjson";
import ProductGrid from "../components/product/ProductGrid";
import { Prisma, Product, ProductPhoto } from "@prisma/client";
import { trpc } from "../utils/trcp";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["products.findAll"]);

  if (isLoading)
    return (
      <div className="antialiased min-h-screen flex items-center justify-center">
        <p className="text-white/40">Loading...</p>
      </div>
    );

  console.log("Products", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Le Store</title>
        <meta
          name="description"
          content="A store generated by Leandro in NextJS + Prisma + tRPC"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Product list</h1>
        <ProductGrid products={data} />
      </main>

      <footer className={styles.footer}>Powered by me.</footer>
    </div>
  );
};

export default Home;
